package containerd

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"foxlab-cli/internal/lab"
)

func TestBuildContainerResolvconfUsesHostAndPublicFallbacks(t *testing.T) {
	host := []byte(`# Generated by NetworkManager
search lab.example
options edns0 trust-ad
nameserver 127.0.0.53
nameserver 192.168.2.1
nameserver 192.168.2.2
`)
	got := string(buildContainerResolvconf(host))
	for _, want := range []string{
		"search lab.example",
		"options edns0 trust-ad",
		"nameserver 192.168.2.1",
		"nameserver 1.1.1.1",
		"nameserver 8.8.8.8",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("managed resolv.conf missing %q:\n%s", want, got)
		}
	}
	for _, unwanted := range []string{"nameserver 127.0.0.53", "nameserver 192.168.2.2"} {
		if strings.Contains(got, unwanted) {
			t.Fatalf("managed resolv.conf contains %q:\n%s", unwanted, got)
		}
	}
}

func TestBuildContainerResolvconfFallsBackWhenHostHasNoNameserver(t *testing.T) {
	got := nameserversInConfig(buildContainerResolvconf([]byte("# Generated by NetworkManager\n")))
	want := []string{"1.1.1.1", "8.8.8.8"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("nameservers = %#v, want %#v", got, want)
	}
}

func TestWriteResolvconfInPlaceKeepsInodeAndSkipsUnchangedWrite(t *testing.T) {
	path := filepath.Join(t.TempDir(), "run", "resolv.conf")
	first := []byte("nameserver 1.1.1.1\n")
	if err := writeResolvconfInPlace(path, first); err != nil {
		t.Fatal(err)
	}
	before, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	beforeModTime := before.ModTime()
	time.Sleep(10 * time.Millisecond)
	if err := writeResolvconfInPlace(path, first); err != nil {
		t.Fatal(err)
	}
	unchanged, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if !unchanged.ModTime().Equal(beforeModTime) {
		t.Fatalf("unchanged file modtime = %v, want %v", unchanged.ModTime(), beforeModTime)
	}
	if err := writeResolvconfInPlace(path, []byte("nameserver 8.8.8.8\n")); err != nil {
		t.Fatal(err)
	}
	after, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if !os.SameFile(before, after) {
		t.Fatal("managed resolv.conf inode changed during update")
	}
}

func TestContainerResolvconfPathUsesFoxlabRunDirectory(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("SUDO_USER", "")
	l := &lab.Lab{ID: "demo"}
	ct := lab.Container{ID: "web"}
	got, err := containerResolvconfPath(l, ct)
	if err != nil {
		t.Fatal(err)
	}
	want := filepath.Join(home, ".foxlab", "run", "resolv", l.ManagedContainerName(ct)+".conf")
	if got != want {
		t.Fatalf("resolv.conf path = %q, want %q", got, want)
	}
}

func TestSyncContainerResolvconfKeepsLastGoodConfigWhenHostReadFails(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("SUDO_USER", "")
	l := &lab.Lab{ID: "demo"}
	ct := lab.Container{ID: "web"}
	hostPath := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(hostPath, []byte("nameserver 192.168.2.1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	managedPath, err := syncContainerResolvconfFrom(l, ct, hostPath)
	if err != nil {
		t.Fatal(err)
	}
	want, err := os.ReadFile(managedPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(hostPath); err != nil {
		t.Fatal(err)
	}
	gotPath, err := syncContainerResolvconfFrom(l, ct, hostPath)
	if err != nil {
		t.Fatalf("sync with missing host resolver: %v", err)
	}
	if gotPath != managedPath {
		t.Fatalf("managed path = %q, want %q", gotPath, managedPath)
	}
	got, err := os.ReadFile(managedPath)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("managed resolver changed after host read failure:\n%s", got)
	}
}

func TestSyncContainerResolvconfReportsMissingHostWithoutLastGoodConfig(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("SUDO_USER", "")
	_, err := syncContainerResolvconfFrom(
		&lab.Lab{ID: "demo"},
		lab.Container{ID: "web"},
		filepath.Join(t.TempDir(), "missing-resolv.conf"),
	)
	if err == nil || !strings.Contains(err.Error(), "read host resolv.conf") {
		t.Fatalf("sync error = %v, want concrete host resolver error", err)
	}
}

func TestManagedResolvconfValidityRequiresUsableNameserver(t *testing.T) {
	path := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(path, []byte("nameserver 127.0.0.53\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if managedResolvconfValid(path) {
		t.Fatal("loopback-only managed resolver considered valid")
	}
	if err := os.WriteFile(path, []byte("nameserver 1.1.1.1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !managedResolvconfValid(path) {
		t.Fatal("public managed resolver considered invalid")
	}
}

func nameserversInConfig(config []byte) []string {
	var nameservers []string
	for _, line := range strings.Split(string(config), "\n") {
		fields := strings.Fields(line)
		if len(fields) > 1 && fields[0] == "nameserver" {
			nameservers = append(nameservers, fields[1])
		}
	}
	return nameservers
}
